package com.bybutter.sisyphus.protobuf.gradle

enum class BuildInPlugin {
    BASIC_GENERATOR,
    COROUTINE_SERVICE_GENERATOR,
    SEPARATED_COROUTINE_SERVICE_GENERATOR,
    RXJAVA_SERVICE_GENERATOR,
    SEPARATED_RXJAVA_SERVICE_GENERATOR,
    RESOURCE_NAME_GENERATOR,
    LITE_DESCRIPTOR_GENERATOR,
    INLINE_DESCRIPTOR_GENERATOR,
    GENERATORS_FROM_SPI
}
