package com.bybutter.sisyphus.middleware.grpc

import com.bybutter.sisyphus.rpc.GrpcServerConstants
import com.bybutter.sisyphus.rpc.RpcService
import io.grpc.ManagedChannelBuilder
import org.springframework.beans.factory.config.ConfigurableListableBeanFactory
import org.springframework.beans.factory.support.AbstractBeanDefinition
import org.springframework.beans.factory.support.BeanDefinitionBuilder
import org.springframework.context.EnvironmentAware
import org.springframework.core.Ordered
import org.springframework.core.annotation.AnnotationUtils
import org.springframework.core.annotation.Order
import org.springframework.core.env.Environment
import org.springframework.stereotype.Component
import kotlin.reflect.full.companionObject

@Component
@Order(Ordered.HIGHEST_PRECEDENCE + 1000)
class LocalClientRepository : ClientRepository, EnvironmentAware {

    private lateinit var environment: Environment

    override fun setEnvironment(environment: Environment) {
        this.environment = environment
    }

    override fun listClientBeanDefinition(beanFactory: ConfigurableListableBeanFactory): List<AbstractBeanDefinition> {
        val localPort = environment.getProperty(GrpcServerConstants.GRPC_PORT_PROPERTY, Int::class.java, GrpcServerConstants.DEFAULT_GRPC_PORT)
        val localChannel = ManagedChannelBuilder.forTarget("localhost:$localPort").usePlaintext().userAgent("Generated by Sisyphus").build()
        val beanDefinitionList = arrayListOf<AbstractBeanDefinition>()
        for (serviceName in beanFactory.getBeanNamesForAnnotation(RpcServiceImpl::class.java)) {
            val serviceBeanDefinition = beanFactory.getBeanDefinition(serviceName)

            val serviceClass = Class.forName(serviceBeanDefinition.beanClassName)
            val rpcService = AnnotationUtils.findAnnotation(serviceClass, RpcService::class.java) ?: continue
            val service = rpcService.client.java.declaringClass
            val stub = service.kotlin.companionObject?.java?.classes?.firstOrNull {
                it.simpleName == "Stub"
            } ?: throw IllegalStateException("Grpc service must have stub class in companion.")
            val clientBeanDefinition = BeanDefinitionBuilder.genericBeanDefinition(rpcService.client.java as Class<Any>) {
                processStub(createGrpcClient(stub, localChannel), beanFactory)
            }
            beanDefinitionList.add(clientBeanDefinition.beanDefinition)
        }
        return beanDefinitionList
    }
}