name: Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: ButterCam/prepare-sisyphus-build@v1
        with:
          dependency-repositories: local,maven,jcenter,portal,snapshot
          snapshot-url: https://oss.sonatype.org/content/repositories/snapshots
          snapshot-username: ${{ secrets.OSSRH_USERNAME }}
          snapshot-password: ${{ secrets.OSSRH_PASSWORD }}
      - name: Build with Gradle
        run: gradle build