name: Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: ButterCam/setup-sisyphus-build@v1
        with:
          dependency-repositories: local,central,jcenter,portal,google,snapshot
          snapshot-url: https://s01.oss.sonatype.org/content/repositories/snapshots
      - name: Build with Gradle
        run: gradle build
