name: Publish

on:
  push:
    branches: [ '**' ]
  release:
    types: [ prereleased, released ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - uses: ButterCam/setup-sisyphus-build@v1
        with:
          dependency-repositories: local,central,jcenter,portal,google,snapshot
          snapshot-url: https://s01.oss.sonatype.org/content/repositories/snapshots
          snapshot-username: ${{ secrets.OSSRH_USERNAME }}
          snapshot-password: ${{ secrets.OSSRH_PASSWORD }}
          release-url: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2
          release-username: ${{ secrets.OSSRH_USERNAME }}
          release-password: ${{ secrets.OSSRH_PASSWORD }}
          gradle-portal-key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle-portal-secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          gpg-key-name: ${{ secrets.GPG_KEY_NAME }}
      - name: Publish with Gradle
        run: gradle publish
      - name: Publish plugins to Gradle Portal
        if: ${{ github.event_name == 'release' }}
        run: gradle publishPlugins
