name: Publish Release

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - uses: ButterCam/prepare-sisyphus-build@31bdc84
        with:
          snapshot: snapshot,mavenSnapshot
          release: release,mavenRelease
          dependency: nexus
          nexus-url: ${{ secrets.NEXUS_PUBLIC_URL }}
          nexus-username: ${{ secrets.NEXUS_USERNAME }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}
          snapshot-url: ${{ secrets.NEXUS_SNAPSHOT_URL }}
          snapshot-username: ${{ secrets.NEXUS_USERNAME }}
          snapshot-password: ${{ secrets.NEXUS_PASSWORD }}
          mavenSnapshot-url: https://oss.sonatype.org/content/repositories/snapshots
          mavenSnapshot-username: ${{ secrets.OSSRH_USERNAME }}
          mavenSnapshot-password: ${{ secrets.OSSRH_PASSWORD }}
          release-url: ${{ secrets.NEXUS_RELEASE_URL }}
          release-username: ${{ secrets.NEXUS_USERNAME }}
          release-password: ${{ secrets.NEXUS_PASSWORD }}
          mavenRelease-url: https://oss.sonatype.org/service/local/staging/deploy/maven2
          mavenRelease-username: ${{ secrets.OSSRH_USERNAME }}
          mavenRelease-password: ${{ secrets.OSSRH_PASSWORD }}
      - name: Build with Gradle
        run: gradle publish